### ISSUE TITLE
Use one hook instead of two

### ISSUE THREAD

**Issue by tsudmi** [arthurdenner/use-lax#30]
Hi,

What do you think of the following approach? This way you could reduce the amount of hooks from 2 to 1.
```javascript
import { useEffect, useRef } from 'react';
import lax from 'lax.js';

function updateLax() {
  lax.update(window.scrollY);
}

// Lax setup must be performed only once.
let setupPerformed = false;

export function useLax() {
  const ref = useRef();

  useEffect(() => {
    if (!setupPerformed) {
      lax.setup();
      setupPerformed = true;
    }

    // No elements -> add listener
    if (lax.elements && lax.elements.length === 0) {
      document.addEventListener('scroll', updateLax, false);
    }

    return () => {
      // Last element about to be removed -> remove listener.
      if (lax.elements && lax.elements.length === 1) {
        document.removeEventListener('scroll', updateLax);
      }
    };
  }, []);

  useEffect(() => {
    const currentNode = ref.current;

    lax.addElement(currentNode);
    return () => {
      lax.removeElement(currentNode);
    };
  }, []);

  return ref;
}
```

**Comment by arthurdenner** [comment]
Hi @tsudmi! 👋 

I like the idea of using only one hook. I'll try to run your suggestion in the examples later to see how it behaves. One difference I noticed is that you didn't run `updateLax`after adding the event listener to the document like we do [here](https://github.com/arthurdenner/use-lax/blob/master/src/index.ts#L14).

**Comment by tsudmi** [comment]
Hi @arthurdenner,

Is it actually needed? For me, it works even without it.

**Comment by arthurdenner** [comment]
I'm not sure. Can you open a PR to change the implementation please?

**Comment by arthurdenner** [comment]
Closing this because v3 exports one hook based on the new of setting up `lax.js`.
