### ISSUE TITLE
/dist folder in v4

### ISSUE THREAD

**Issue by elrumordelaluz** [arthurdenner/use-lax#442]
Hi,
Seems that the `v4` is [not published properly](https://unpkg.com/use-lax@4.0.0/dist). 
Getting the following error updating both packages in the [demo sandbox](https://codesandbox.io/s/use-lax-example-forked-f66el).

<img width="1534" alt="Screenshot 2021-02-02 at 17 47 20" src="https://user-images.githubusercontent.com/784056/106633158-d0e6bf80-657e-11eb-896f-9b45e60ae3b8.png">

**Comment by arthurdenner** [comment]
Hi @elrumordelaluz! 👋🏽 

Thank you very much for reporting this.

After some investigation, I found why the release failed and fixed it in #444.

You can now update to `4.0.2` and try the new hooks.
